### ISSUE TITLE
Figures are missing

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/isotc204-glossary#12]
https://isotc204.geolexica.org/concepts/3.3.1.1/
<img width="1067" alt="Screen Shot 2022-08-18 at 10 07 56 PM" src="https://user-images.githubusercontent.com/11865/185415591-c95cdf43-da8d-48f3-a8fc-82eb38f9d07d.png">

**Comment by HassanAkbar** [comment]
@ronaldtse How do we want to add the images? 
Should we add the images on the concept page or add all the images on a separate page and then link them to the concept page?

**Comment by ronaldtse** [comment]
For the images that is part of the concept, e.g. this one, add to this page inline.

For images that are views of multiple concepts, they need to go on new pages.
